title: FFSETIT Homepage
author:
  name: Peter Barnes
  email: ffsetit@gmail.com
description: Bookmark this to keep an eye on my project updates!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: instagram,  user_url: "https://www.instagram.com/jvd_bvba/?hl=nl" }
    - { platform: facebook, user_url: "https://www.facebook.com/Van-Driessche-Jente-Bouw-Renovatiebedrijf-1376218165755069/" }  